# Define BIDS entities to loop over
loop_over:
  - subject
  - session
  - run

# Define how each data type (suffix) should be handled.
T1w:
  plain_set: {}

T2w:
  plain_set: {}

# Plain DWI (no phase encoding direction)
dwi:
  plain_set: {}
  additional_extensions:
    - bvec
    - bval

dwi_ap_pa:
  named_set:
    ap:
      direction: dir-AP
    pa:
      direction: dir-PA
  required: ["ap", "pa"]
  additional_extensions:
    - bvec
    - bval
  suffix_maps_to: "dwi"

sbref:
  plain_set:
    exclude_entities:
      - direction

sbref_ap_pa:
  named_set:
    ap:
      direction: dir-AP
    pa:
      direction: dir-PA
  required: ["ap", "pa"]
  suffix_maps_to: "sbref"

epi:
  plain_set: {}

epi_ap_pa:
  suffix_maps_to: "epi"
  named_set:
    ap:
      direction: "dir-AP"
    pa:
      direction: "dir-PA"
  required: ["ap", "pa"]